tag:
  fields:
    entry:
      required: true
      selector:
        config_entry:
          integration: "imap_no_ssl"
    uid:
      required: true
      example: "12"
      selector:
        text:
    tag:
      required: true
      example: "tag"
      selector:
        text:
seen:
  fields:
    entry:
      required: true
      selector:
        config_entry:
          integration: "imap_no_ssl"
    uid:
      required: true
      example: "12"
      selector:
        text:
move:
  fields:
    entry:
      required: true
      selector:
        config_entry:
          integration: "imap_no_ssl"
    uid:
      required: true
      example: "12"
      selector:
        text:
    seen:
      selector:
        boolean:
    target_folder:
      required: true
      example: "INBOX.Trash"
      selector:
        text:

delete:
  fields:
    entry:
      required: true
      selector:
        config_entry:
          integration: "imap_no_ssl"
    uid:
      example: "12"
      required: true
      selector:
        text:

fetch:
  fields:
    entry:
      required: true
      selector:
        config_entry:
          integration: "imap_no_ssl"
    uid:
      required: true
      example: "12"
      selector:
        text:
